### ISSUE TITLE
How about adding cookies?

### ISSUE THREAD

**Issue by aytacmalkoc** [Fcmam5/nightly.js#10]
Hi, thank you for this library. Are you considering adding a feature that we can use cookies in the near future?

**Comment by Fcmam5** [comment]
We are already using localStorage for keeping the user preference:
 ```js
var Nightly = new Nightly(nightModeConfig, true);
```

The second parameter is whether to store the preference last state or not, but why do you think that we should use cookies?

And if you didn't know that we already have this storage thingy that's on me and I should highlight that in the documentation :disappointed:
