### ISSUE TITLE
Suggest features/options

### ISSUE THREAD

**Issue by Fcmam5** [Fcmam5/nightly.js#5]
What options should we add to Nightly.js?
Is it interesting if we write Nightly.js plugins for famous frameworks such as Bootstrap?

Any other suggestions?

**Comment by RihanArfan** [comment]
It would be useful if I could disable Nightly.js from changing links, etc.
I'll probably figure out how to do this in the few next hours, but if it's not possible, I guess here's a suggestion.

**Comment by Fcmam5** [comment]
What do think of the following suggestions: 
1. We pass a parameter called "exclude" with an array of tags that we need to exclude from changing?
2. We pass a falsy value for the given parameter, example `new Nightly(true, {links: false});` to disable links style changing.

For the moment, this could be done by passing the same css class to in both `apply` and `to` in the constructor, for example:

```javascript
var Nightly = new Nightly(true, {
         classes: [
           {
             apply: 'myClass', 
             to: 'myClass',
           },
         ]
       }
     );
```

**Comment by RihanArfan** [comment]
I do like the idea of the 2nd solution.
