### ISSUE TITLE
Nested elements

### ISSUE THREAD

**Issue by raidski20** [Fcmam5/nightly.js#9]
for example if i have this css selector: 
.exp .info .link{...}

if i try to write this: 
var Nightly = new Nightly({
    classes: [
      {
        apply: 'color-darker',
        to: 'exp info link'
      },
],
});
it doesn't work !

**Comment by Fcmam5** [comment]
It wasn't to supposed to work for this case since it only applies a CSS class to an element with a defined CSS class.
But, it makes sense to adjust it to work for your case. That would make it easier to integrate with less hustling and maybe without readjusting your HTML elements.
Thank you for reporting this!

Now this should work for you :)

```html
<div class="exp">
  <div class="info">
    <div class="link bold"></div>
  </div>
</div>

<script>

var Nightly = new Nightly({
  classes: [
    {
      apply: 'color-darker',
      to: '.exp .info .link.bold'
    },
  ],
});

</script>
```

**Comment by raid21** [comment]
It adds the new class now but i'm not sure why it doesn't override the old one, i've those two classes: 
.news .card-body {background: #faf8f0;}
// and this should make the background black
.bg-darker{background-color: #060606;}

and javascript: 
var Nightly = new Nightly({
    classes: [
      {
        apply: 'color-darker',
        to: '.news .card .card-body'
      }
    ],
});

and the html is: 
<div id="news" class="news">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body"></div>
                   </div>
         </div>
</div>

it doesn't override the background color of the card !
![t](https://user-images.githubusercontent.com/26503233/79157434-751f3000-7dcc-11ea-8a2e-4ab8f6166e7a.png)
